steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/hackathon-agent-app:$COMMIT_SHA'
      - .

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - 'gcr.io/$PROJECT_ID/hackathon-agent-app:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - hackathon-agent-app
      - '--image=gcr.io/$PROJECT_ID/hackathon-agent-app:$COMMIT_SHA'
      - '--region=europe-west2'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=8080'

images:
  - 'gcr.io/$PROJECT_ID/hackathon-agent-app:$COMMIT_SHA'
